import "server-only";

import { getPublicSupabaseConfig } from "@/lib/public-env";

export class ConfigurationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ConfigurationError";
  }
}

export function requireSupabaseServerConfig() {
  const publicConfig = getPublicSupabaseConfig();
  const secretKey = process.env.SUPABASE_SECRET_KEY?.trim();

  if (!publicConfig || !secretKey) {
    throw new ConfigurationError(
      "Supabase is not configured. Set NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY, and SUPABASE_SECRET_KEY.",
    );
  }

  return { ...publicConfig, secretKey };
}

export function requireApplicationSecrets() {
  const guestCartPepper = process.env.GUEST_CART_TOKEN_PEPPER?.trim();
  const hmacSecret = requireHmacSecret();
  if (!guestCartPepper || !hmacSecret) {
    throw new ConfigurationError("GUEST_CART_TOKEN_PEPPER and APP_HMAC_SECRET are required for persistent mutations.");
  }
  return { guestCartPepper, hmacSecret };
}

export function requireHmacSecret() {
  const hmacSecret = process.env.APP_HMAC_SECRET?.trim();
  if (!hmacSecret) throw new ConfigurationError("APP_HMAC_SECRET is required for request integrity controls.");
  return hmacSecret;
}

export function requireCloudinaryConfig() {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME?.trim();
  const apiKey = process.env.CLOUDINARY_API_KEY?.trim();
  const apiSecret = process.env.CLOUDINARY_API_SECRET?.trim();
  if (!cloudName || !apiKey || !apiSecret) {
    throw new ConfigurationError(
      "Cloudinary is not configured. Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET.",
    );
  }
  if (!/^[A-Za-z0-9_-]+$/.test(cloudName)) throw new ConfigurationError("CLOUDINARY_CLOUD_NAME has an invalid format.");
  return {
    cloudName,
    apiKey,
    apiSecret,
    privateReadTtlSeconds: parseCloudinaryTtl(process.env.CLOUDINARY_PRIVATE_READ_URL_TTL_SECONDS),
  };
}

function parseCloudinaryTtl(value: string | undefined) {
  const parsed = value === undefined || value.trim() === "" ? 900 : Number(value);
  if (!Number.isInteger(parsed) || parsed < 60 || parsed > 3600) {
    throw new ConfigurationError("CLOUDINARY_PRIVATE_READ_URL_TTL_SECONDS must be an integer between 60 and 3600 seconds.");
  }
  return parsed;
}

export function requireRazorpayConfig() {
  const keyId = process.env.RAZORPAY_KEY_ID?.trim();
  const keySecret = process.env.RAZORPAY_KEY_SECRET?.trim();
  const mode = process.env.RAZORPAY_MODE?.trim() || "test";

  if (!keyId || !keySecret) {
    throw new ConfigurationError("Razorpay is not configured. Set RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET.");
  }
  if (mode !== "test" && mode !== "live") throw new ConfigurationError("RAZORPAY_MODE must be either test or live.");
  if (!/^rzp_(test|live)_[A-Za-z0-9]+$/.test(keyId)) throw new ConfigurationError("RAZORPAY_KEY_ID has an invalid format.");
  if (mode === "test" && !keyId.startsWith("rzp_test_")) throw new ConfigurationError("Test mode requires a Razorpay test key.");
  if (mode === "live" && !keyId.startsWith("rzp_live_")) throw new ConfigurationError("Live mode requires a Razorpay live key.");

  return { keyId, keySecret, mode } as const;
}

export function requireRazorpayWebhookSecret() {
  const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET?.trim();
  if (!webhookSecret) throw new ConfigurationError("RAZORPAY_WEBHOOK_SECRET is required for Razorpay webhooks.");
  return webhookSecret;
}

export function requireCronSecret() {
  const cronSecret = process.env.CRON_SECRET?.trim();
  if (!cronSecret) throw new ConfigurationError("CRON_SECRET is required to authorize scheduled jobs.");
  return cronSecret;
}

export function isProduction() {
  return process.env.NODE_ENV === "production";
}

// Secrets generated by us (not issued by a third party): they must be long and random.
// Razorpay-issued values (RAZORPAY_KEY_SECRET) are excluded because their length is fixed
// by Razorpay and can be shorter than 32 characters.
const OWNER_GENERATED_SECRETS = [
  "APP_HMAC_SECRET",
  "GUEST_CART_TOKEN_PEPPER",
  "CRON_SECRET",
  "RAZORPAY_WEBHOOK_SECRET",
] as const;

const MIN_SECRET_LENGTH = 32;

// Values that must never ship with a `.env.example` placeholder in production.
const REQUIRED_PRODUCTION_VALUES = [
  "NEXT_PUBLIC_SITE_URL",
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SECRET_KEY",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "RAZORPAY_KEY_ID",
  "RAZORPAY_KEY_SECRET",
  "RAZORPAY_WEBHOOK_SECRET",
  "GUEST_CART_TOKEN_PEPPER",
  "APP_HMAC_SECRET",
  "CRON_SECRET",
] as const;

const PLACEHOLDER_PATTERN = /replace|your-project-ref|changeme|example\.com/i;

/**
 * Aggregate boot-time validation for all server secrets. Invoked from
 * `instrumentation.ts#register()` so the process refuses to start when a required
 * secret is missing, malformed, still a placeholder, or too weak. Never logs values.
 *
 * Presence/format checks run in every environment; placeholder rejection and the
 * distributed-rate-limiting requirement apply only in production.
 */
export function assertServerEnv(options: { production?: boolean } = {}): void {
  const production = options.production ?? isProduction();
  const errors: string[] = [];

  const collect = (validate: () => void) => {
    try {
      validate();
    } catch (error) {
      if (error instanceof ConfigurationError) errors.push(error.message);
      else throw error;
    }
  };

  collect(() => requireSupabaseServerConfig());
  collect(() => requireCloudinaryConfig());
  collect(() => requireRazorpayConfig());
  collect(() => requireRazorpayWebhookSecret());
  collect(() => requireApplicationSecrets());
  collect(() => requireCronSecret());

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (!siteUrl) {
    errors.push("NEXT_PUBLIC_SITE_URL is required for metadata, sitemap, and Razorpay submission.");
  } else {
    try {
      const parsed = new URL(siteUrl);
      if (production && parsed.protocol !== "https:") {
        errors.push("NEXT_PUBLIC_SITE_URL must use https in production.");
      }
    } catch {
      errors.push("NEXT_PUBLIC_SITE_URL must be a valid absolute URL.");
    }
  }

  for (const name of OWNER_GENERATED_SECRETS) {
    const value = process.env[name]?.trim();
    if (value && value.length < MIN_SECRET_LENGTH) {
      errors.push(`${name} must be at least ${MIN_SECRET_LENGTH} characters (use >= 32 random bytes).`);
    }
  }

  if (production) {
    for (const name of REQUIRED_PRODUCTION_VALUES) {
      const value = process.env[name]?.trim();
      if (value && PLACEHOLDER_PATTERN.test(value)) {
        errors.push(`${name} still contains a placeholder value; set the real production secret.`);
      }
    }

    const upstashUrl = process.env.UPSTASH_REDIS_REST_URL?.trim();
    const upstashToken = process.env.UPSTASH_REDIS_REST_TOKEN?.trim();
    if (!upstashUrl || !upstashToken) {
      errors.push(
        "UPSTASH_REDIS_REST_URL and UPSTASH_REDIS_REST_TOKEN are required in production; rate limiting fails closed (503) otherwise.",
      );
    }
  }

  if (errors.length > 0) {
    throw new ConfigurationError(
      `Server environment is misconfigured (${errors.length} problem${errors.length === 1 ? "" : "s"}):\n- ${errors.join("\n- ")}`,
    );
  }
}
